export type AppIconName =
  | 'menu'
  | 'search'
  | 'bell'
  | 'user'
  | 'dashboard'
  | 'cart'
  | 'chart'
  | 'credit-card'
  | 'wallet'
  | 'refresh'
  | 'receipt'
  | 'trending-up'
  | 'trending-down'
  | 'store'
  | 'chart-pie'
  | 'truck'
  | 'dots'
  | 'brand-paypal'
  | 'sun'
  | 'moon'
  | 'file-text'
  | 'ticket'
  | 'trash'
  | 'check'
  | 'chevron-left'
  | 'chevron-right'
  | 'eye'
  | 'edit'
  | 'star'
  | 'star-half'
  | 'star-off'
  | 'heart'
  | 'heart-filled'
  | 'filter'
  | 'select'
  | 'hand-stop'
  | 'rectangle'
  | 'circle'
  | 'line'
  | 'arrow-right'
  | 'pencil'
  | 'cursor-text'
  | 'eraser'
  | 'arrow-back-up'
  | 'arrow-forward-up'
  | 'zoom-in'
  | 'zoom-out'
  | 'download'
  | 'chalkboard'
  | 'x'
  | 'logout';

export const iconSources: Record<AppIconName, string> = {
  menu: 'assets/icons/menu-2.svg',
  search: 'assets/icons/search.svg',
  bell: 'assets/icons/bell.svg',
  user: 'assets/icons/user-circle.svg',
  dashboard: 'assets/icons/layout-dashboard.svg',
  cart: 'assets/icons/shopping-cart.svg',
  chart: 'assets/icons/chart-bar.svg',
  'credit-card': 'assets/icons/credit-card.svg',
  wallet: 'assets/icons/wallet.svg',
  refresh: 'assets/icons/refresh.svg',
  receipt: 'assets/icons/receipt.svg',
  'trending-up': 'assets/icons/trending-up.svg',
  'trending-down': 'assets/icons/trending-down.svg',
  store: 'assets/icons/building-store.svg',
  'chart-pie': 'assets/icons/chart-pie.svg',
  truck: 'assets/icons/truck.svg',
  dots: 'assets/icons/dots.svg',
  'brand-paypal': 'assets/icons/brand-paypal.svg',
  sun: 'assets/icons/sun.svg',
  moon: 'assets/icons/moon.svg',
  'file-text': 'assets/icons/file-text.svg',
  ticket: 'assets/icons/ticket.svg',
  trash: 'assets/icons/trash.svg',
  check: 'assets/icons/check.svg',
  'chevron-left': 'assets/icons/chevron-left.svg',
  'chevron-right': 'assets/icons/chevron-right.svg',
  eye: 'assets/icons/eye.svg',
  edit: 'assets/icons/edit.svg',
  star: 'assets/icons/star.svg',
  'star-half': 'assets/icons/star-half.svg',
  'star-off': 'assets/icons/star-off.svg',
  heart: 'assets/icons/heart.svg',
  'heart-filled': 'assets/icons/heart-filled.svg',
  filter: 'assets/icons/filter.svg',
  select: 'assets/icons/select.svg',
  'hand-stop': 'assets/icons/hand-stop.svg',
  rectangle: 'assets/icons/rectangle.svg',
  circle: 'assets/icons/circle.svg',
  line: 'assets/icons/line.svg',
  'arrow-right': 'assets/icons/arrow-right.svg',
  pencil: 'assets/icons/pencil.svg',
  'cursor-text': 'assets/icons/cursor-text.svg',
  eraser: 'assets/icons/eraser.svg',
  'arrow-back-up': 'assets/icons/arrow-back-up.svg',
  'arrow-forward-up': 'assets/icons/arrow-forward-up.svg',
  'zoom-in': 'assets/icons/zoom-in.svg',
  'zoom-out': 'assets/icons/zoom-out.svg',
  download: 'assets/icons/download.svg',
  chalkboard: 'assets/icons/chalkboard.svg',
  x: 'assets/icons/x.svg',
  logout: 'assets/icons/logout.svg',
};
